SCREEN_WIDTH = 512
SCREEN_HEIGHT = 640

GAMEFIELD_LEFT_BORDER = SCREEN_WIDTH / 2 - GAMEFIELD_WIDTH / 2 + 1
GAMEFIELD_RIGHT_BORDER = GAMEFIELD_LEFT_BORDER + GAMEFIELD_WIDTH - 2
GAMEFIELD_TOP_BORDER = 0 + 1
GAMEFIELD_BOTTOM_BORDER = SCREEN_HEIGHT - 1

PLAYER_MAX_SPEED = 5
PLAYER_WIDTH = 16
PLAYER_HEIGHT = 40

BLOCK_WIDTH = 16
BLOCK_COUNT = 16

GAMEFIELD_WIDTH = BLOCK_WIDTH * BLOCK_COUNT
GAMEFIELD_HEIGHT = SCREEN_HEIGHT
