SCREEN_WIDTH = 512
SCREEN_HEIGHT = 640
GAMEFIELD_WIDTH = 256
GAMEFIELD_HEIGHT = SCREEN_HEIGHT
GAMEFIELD_LEFT_BORDER = SCREEN_WIDTH / 2 - GAMEFIELD_WIDTH / 2 + 1
GAMEFIELD_RIGHT_BORDER = GAMEFIELD_LEFT_BORDER + GAMEFIELD_WIDTH - 2
GAMEFIELD_TOP_BORDER = 0 + 1
GAMEFIELD_BOTTOM_BORDER = SCREEN_WIDTH - 1
<<<<<<< HEAD
=======
PLAYER_MAX_SPEED = 5
PLAYER_WIDTH = 16
PLAYER_HEIGHT = 40
BLOCK_COUNT = 16
BLOCK_WIDTH = GAMEFIELD_WIDTH / BLOCK_COUNT
>>>>>>> 0e6bbc0cfb125b7712d095c63ff3065e9230d79d
